# Set the actions' name
name: Yaml File Linter

# Event trigger
on:
  push:
    branches:
        - "main"
        - "hotfix/staline"

jobs:
    pull_repo:
        runs-on: ubuntu-latest
        steps:
          - name: Pull my repository
            uses: actions/checkout@v6
          - name: Collection info
            run: ls -la